// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhlhqypygmsqfperejvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhobGhxeXB5Z21zcWZwZXJlanZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjE1NzQsImV4cCI6MjA3MDIzNzU3NH0.Grgub19jTniruZTy7wXy88oW8XG9GTtJQ11_-cRWS64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});